### ISSUE TITLE
Error when adding ngs coverage to h5 file.

### ISSUE THREAD

**Issue by xiekunwhy** [weberlab-hhu/Helixer#148] opened 2024-11-03 12:48 UTC
**Describe the bug**
Error when adding ngs coverage to h5 file.
**To Reproduce**
adding ngs coverage to h5 file.
Commands ran, especially any commands that threw an error
command:
```
/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/bin/python /public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/bin/import2geenuff.py --fasta gra.hic.fa --gff3 gra.gffread.ss.c.gene.gff --db-path gra.gffread.ss.c.sqlite3 --log-file gra.gffread.ss.c.log --species train

/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/bin/python /public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/bin/geenuff2h5.py --h5-output-path gra.gffread.ss.c.h5 --input-db-path gra.gffread.ss.c.sqlite3

cp gra.gffread.ss.c.h5 gra.gffread.ss.c.backup.h5

source /public2/home/sl_qybio/sl_qybio/miniforge3/bin/activate helixer
/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/bin/python /public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/site-packages/helixer/evaluation/add_ngs_coverage.py -s train --unstranded --bam gra.merge.sort.bam --h5-data gra.gffread.ss.c.h5 --dataset-prefix rnaseq --threads 1
```
**Error**
The command line output including the error thrown.
```
start, end 0 255842
(b'Chr01', 0, 36794)
Chr01: chunks from 0-36794
Traceback (most recent call last):
  File "/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/site-packages/helixer/evaluation/add_ngs_coverage.py", line 418, in cage_coverage_from_coord_to_h5
    shutil.rmtree(d)  # rm -r
  File "/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/shutil.py", line 731, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/shutil.py", line 729, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: 'memmap_dir_91520057901807361798938075985984269058'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/site-packages/helixer/evaluation/add_ngs_coverage.py", line 530, in <module>
    main(args.species,
  File "/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/site-packages/helixer/evaluation/add_ngs_coverage.py", line 466, in main
    cage_coverage_from_coord_to_h5(
  File "/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/site-packages/helixer/evaluation/add_ngs_coverage.py", line 420, in cage_coverage_from_coord_to_h5
    shutil.rmtree(d)
  File "/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/shutil.py", line 731, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/public2/home/sl_qybio/sl_qybio/miniforge3/envs/helixer/lib/python3.10/shutil.py", line 729, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: 'memmap_dir_91520057901807361798938075985984269058'

```

**Expected behavior**
something wrong when adding coverage to h5 file.

**Environment (please complete the following information):**
 - OS: Linux
 - conda
 - no

**Additional context**

**Comment by xiekunwhy** [comment] 2024-11-06 12:39
It seems that, change ``` shutil.rmtree(d) ``` to  ```shutil.rmtree(d, ignore_errors=True)``` in add_ngs_coverage.py solved the problem.

**Comment by felicitas215** [comment] 2024-11-06 13:11
Reply to the first comment:
```
singularity run helixer-docker_helixer_v0.3.3_cuda_11.8.0-cudnn8.sif /home/helixer_user/Helixer/helixer/evaluation/add_ngs_coverage.py <rest_of_your_command_as_usual>
```
The `--nv` parameter is only necessary for GPU operations, `add_ngs_coverage.py` doesn't use/need the GPU.
  
Reply to the second comment:
This will indeed allow your process to run, but you will be left with a lot of memmap_dir folders to delete manually, correct?

**Comment by xiekunwhy** [comment] 2024-11-06 13:47
By the way, ```add_ngs_coverage.py``` is too slow for medium or large genome, any suggestions to speed up this step?
Is it possible to split genome by chromosome and add each independently, than merge chromosome-wise h5 files ?
Is there an example command line to merge chromosome-wise h5 files ?

Best,
Kun

**Comment by felicitas215** [comment] 2024-11-06 14:10
What is too slow in this case, how long does it take? You could always try if using more threads works. There is no example script or possibility to split the h5 file by chromosome to add to each a separate chromosome bam file. We don't plan to add something like this for the foreseeable future.
If `add_ngs_coverage.py` is working now as intended I will close this issue.

**Comment by felicitas215** [comment] 2024-11-06 14:42
Thanks for your feedback, we will bear it in mind for future releases.

**Closed by felicitas215** 2024-11-06 14:42 UTC
